logging.config=classpath:logback-spring.xml
spring.main.banner-mode=off
# actuators
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.web.client.request.autotime.enabled=false

server.tomcat.threads.min-spare=50
server.tomcat.threads.max=100
server.shutdown=graceful

dpi.pagesize=5000
kjernetidStart=07:00:00
kjernetidSlutt=23:00:00