kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: AZURE_APP_TOKEN_URL
      value: {{AZURE_APP_TOKEN_URL}}
    - name: DOKMET_SCOPE
      value: {{DOKMET_SCOPE}}
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: {{DIGDIR_KRR_PROXY_SCOPE}}
    - name: DOKDISTDPI_PROXY_HOST
      value: {{DOKDISTDPI_PROXY_HOST}}
    - name: DOKDISTDPI_PROXY_PORT
      value: "{{DOKDISTDPI_PROXY_PORT}}"
    - name: DPI_URL
      value: {{ DPI_URL }}
    - name: DPI_MPCKANAL
      value: {{ DPI_MPCKANAL }}
    - name : DOKDISTDPI_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTDPI_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name : DOKDISTDPI_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTDPI_ENDPOINTS_DOKDISTADMIN_URL }}
    - name: DOKUMENTTYPEINFO_V4_URL
      value: {{ DOKUMENTTYPEINFO_V4_URL }}
    - name: VARSELINFO_URL
      value: {{ VARSELINFO_URL }}
    - name: DIGDIR_KRR_PROXY_URL
      value: {{ DIGDIR_KRR_PROXY_URL }}
    - name: MASKINPORTEN_URL
      value: {{ MASKINPORTEN_URL }}
    - name: MASKINPORTEN_AUDIENCE
      value: {{ MASKINPORTEN_AUDIENCE }}
    - name: SAF_GRAPHQL_URL
      value: {{ SAF_GRAPHQL_URL }}
    - name: JURIDISKLOGG_URL
      value: {{ JURIDISKLOGG_URL }}
    - name: SECURITY_TOKEN_SERVICE_URL
      value: {{ SECURITY_TOKEN_SERVICE_URL }}
    - name: MQGATEWAY01_CHANNEL_NAME
      value: {{ MQGATEWAY01_CHANNEL_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_CHANNEL_ENABLETLS
      value: "{{ MQGATEWAY01_CHANNEL_ENABLETLS }}"
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME}}
    - name: DOKDISTDPI_QDIST011_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTDPI_QDIST014_KVITTERING_FRA_DPI_QUEUENAME
      value: {{ DOKDISTDPI_QDIST014_KVITTERING_FRA_DPI_QUEUENAME }}
    - name: DOKDISTDPI_QDIST014_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTDPI_QDIST014_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTDPI_QDIST011_DIST_TIL_DPI_KBQ_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_DIST_TIL_DPI_KBQ_QUEUENAME }}
    - name: DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME
      value: {{ DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME }}
    - name: APPD_NAME
      value: {{ APPD_NAME }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  leaderElection: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 3096Mi
    requests:
      cpu: 1024m
      memory: 1512Mi
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: digitalpostinnbygger:send
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTDPI2 }}
        mountPath: "/secrets/serviceuser/srvdokdistdpi-2"
      - kvPath: {{ DOKDISTDPI_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
      - kvPath: {{ VIRKSOMHETSSERTIFIKAT_VAULT }}
        mountPath: "/secrets/virksomhetssertifikat/sdp"
      - kvPath: {{ APPDYNAMICS }}
        mountPath: /var/run/secrets/nais.io/appdynamics
      - kvPath: {{ DOKDISTDPI_CERT }}
        mountPath: /var/run/secrets/nais.io/certificate
  azure:
    application:
      enabled: true