kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DPI_URL
      value: {{ DPI_URL }}
    - name: DPI_MPCKANAL
      value: {{ DPI_MPCKANAL }}
    - name: ADMINISTRERFORSENDELSE_URL
      value: {{ ADMINISTRERFORSENDELSE_URL }}
    - name: DOKUMENTTYPEINFO_V4_URL
      value: {{ DOKUMENTTYPEINFO_V4_URL }}
    - name: VARSELINFO_V1_URL
      value: {{ VARSELINFO_V1_URL }}
    - name: DKI_API_URL
      value: {{ DKI_API_URL }}
    - name: MASKINPORTEN_URL
      value: {{ MASKINPORTEN_URL }}
    - name: MASKINPORTEN_AUDIENCE
      value: {{ MASKINPORTEN_AUDIENCE }}
    - name: S3_STORAGE_URL
      value: {{ S3_STORAGE_URL }}
    - name: SAF_GRAPHQL_URL
      value: {{ SAF_GRAPHQL_URL }}
    - name: LAGREJURIDISKLOGG_REST_URL
      value: {{ LAGREJURIDISKLOGG_REST_URL }}
    - name: SECURITY_TOKEN_SERVICE_URL
      value: {{ SECURITY_TOKEN_SERVICE_URL }}
    - name: MQGATEWAY01_CHANNELNAME
      value: {{ MQGATEWAY01_CHANNELNAME }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME}}
    - name: DOKDISTDPI_QDIST011_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTDPI_QDIST014_KVITTERING_FRA_DPI_QUEUENAME
      value: {{ DOKDISTDPI_QDIST014_KVITTERING_FRA_DPI_QUEUENAME }}
    - name: DOKDISTDPI_QDIST014_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTDPI_QDIST014_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME
      value: {{ DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME }}
    - name: APPD_NAME
      value: {{ APPD_NAME }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  leaderElection: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1536Mi
    requests:
      cpu: 60m
      memory: 1024Mi
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: digitalpostinnbygger:send
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTDPI2 }}
        mountPath: "/secrets/serviceuser/srvdokdistdpi-2"
      - kvPath: {{ DOKDISTDPI_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
      - kvPath: {{ VIRKSOMHETSSERTIFIKAT_VAULT }}
        mountPath: "/secrets/virksomhetssertifikat/sdp"
      - kvPath: { { APPDYNAMICS } }
        mountPath: /var/run/secrets/nais.io/appdynamics

